# Generated by Django 3.2.8 on 2021-11-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kadai_app', '0008_auto_20211012_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='attach2',
        ),
        migrations.RemoveField(
            model_name='play',
            name='attach3',
        ),
    ]
