# Generated by Django 2.2.2 on 2021-09-30 01:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai_app', '0003_auto_20210929_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='attach2',
            field=models.FileField(default='www', upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp3'])], verbose_name='添付ファイル'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='play',
            name='attach3',
            field=models.FileField(default='ww', upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp3'])], verbose_name='添付ファイル'),
            preserve_default=False,
        ),
    ]
