# Generated by Django 2.2.2 on 2021-09-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai_app', '0005_auto_20210930_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='attach1',
            field=models.FileField(upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='play',
            name='attach10',
            field=models.FileField(blank=True, default='なし', null=True, upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='play',
            name='attach2',
            field=models.FileField(blank=True, default='なし', null=True, upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='play',
            name='attach3',
            field=models.FileField(blank=True, default='なし', null=True, upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='play',
            name='attach4',
            field=models.FileField(blank=True, default='なし', null=True, upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='play',
            name='attach5',
            field=models.FileField(blank=True, default='なし', null=True, upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='play',
            name='attach6',
            field=models.FileField(blank=True, default='なし', null=True, upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='play',
            name='attach7',
            field=models.FileField(blank=True, default='なし', null=True, upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='play',
            name='attach8',
            field=models.FileField(blank=True, default='なし', null=True, upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='play',
            name='attach9',
            field=models.FileField(blank=True, default='なし', null=True, upload_to='', verbose_name='添付ファイル'),
        ),
    ]
