# Generated by Django 2.2.2 on 2021-10-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kadai_app', '0007_auto_20211001_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='attach10',
        ),
        migrations.RemoveField(
            model_name='play',
            name='attach4',
        ),
        migrations.RemoveField(
            model_name='play',
            name='attach5',
        ),
        migrations.RemoveField(
            model_name='play',
            name='attach6',
        ),
        migrations.RemoveField(
            model_name='play',
            name='attach7',
        ),
        migrations.RemoveField(
            model_name='play',
            name='attach8',
        ),
        migrations.RemoveField(
            model_name='play',
            name='attach9',
        ),
    ]
