# Generated by Django 3.2.8 on 2021-11-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai_app', '0009_auto_20211124_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
