# Generated by Django 2.2.2 on 2021-09-22 11:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('attach1', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['.mp3'])], verbose_name='添付ファイル')),
                ('attach2', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['.mp3'])], verbose_name='添付ファイル')),
                ('attach3', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['.mp3'])], verbose_name='添付ファイル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Play',
            },
        ),
    ]
