# Generated by Django 2.2.2 on 2021-10-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai_app', '0006_auto_20210930_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='attach10',
            field=models.FileField(default='なし', upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='play',
            name='attach2',
            field=models.FileField(default='なし', upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='play',
            name='attach3',
            field=models.FileField(default='なし', upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='play',
            name='attach4',
            field=models.FileField(default='なし', upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='play',
            name='attach5',
            field=models.FileField(default='なし', upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='play',
            name='attach6',
            field=models.FileField(default='なし', upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='play',
            name='attach7',
            field=models.FileField(default='なし', upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='play',
            name='attach8',
            field=models.FileField(default='なし', upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='play',
            name='attach9',
            field=models.FileField(default='なし', upload_to='', verbose_name='添付ファイル'),
        ),
    ]
